### VITAMINS INDEX
GET http://localhost:3000/vitamins.json


### VITAMINS SHOW
GET http://localhost:3000/vitamins/1.json


### VITAMINS CREATE
POST http://localhost:3000/vitamins.json
# Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NjE2ODk2Mjh9.g6epaGkcCgj9dJUqucOaFrcafxbhFXXUlWjvtWNSDOU
Content-Type: application/json

{
  "name": "Vitamin B Complex",
  "description": "",
  "sources": "",
  "used_for": ""
}

### VITAMINS UPDATE
PATCH http://localhost:3000/vitamins/3.json
# Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NjE2ODk2Mjh9.g6epaGkcCgj9dJUqucOaFrcafxbhFXXUlWjvtWNSDOU
Content-Type: application/json

{
  "name": "Vitamin B3",
  "description": "Helps convert food into energy",
  "sources": "",
  "used_for": ""
}

### VITAMINS DELETE
DELETE http://localhost:3000/vitamins/6.json

###############USERS#######################################

### user create (sign up)
POST http://localhost:3000/users
Content-Type: application/json

{
  "first_name": "Peter",
  "last_": "Dubois",
  "email": "peter@peter.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions
Content-Type: application/json

{
  "email": "mike@mike.com",
  "password": "password"
}


###############LIST-OF-VITAMINS#######################################

### LIST-OF-VITAMINS INDEX
GET http://localhost:3000/lists_of_vitamins.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo0LCJleHAiOjE2NjMyODUzNzV9.QeOzDh26izNmlQ4wkTglm1unuO6Y7NXf_zRBOlL5rWQ

### LIST-OF-VITAMINS create
POST http://localhost:3000/lists_of_vitamins.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NjMyOTcwNTV9.yLQ1KMBjDH6DqQbc9xKbuSKbMAi2HMV1fzxhPJr30Ck
Content-Type: application/json

{

 "vitamin_id": 7,
 "quantity": 4

}

### LIST-OF-VITAMINS UPDATE
PATCH http://localhost:3000/lists_of_vitamins/6
Content-Type: application/json

{
"intake_quantity": 0,
"intake_quantity_left": 4
}

### LIST-OF-VITAMINS DELETE
DELETE http://localhost:3000/lists_of_vitamins/7.json