### VITAMINS INDEX
GET http://localhost:3000/vitamins.json


### VITAMINS SHOW
GET http://localhost:3000/vitamins/7.json


### VITAMINS CREATE
POST http://localhost:3000/vitamins.json
# Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NjE2ODk2Mjh9.g6epaGkcCgj9dJUqucOaFrcafxbhFXXUlWjvtWNSDOU
Content-Type: application/json

{
  "name": "Vitamin B Complex",
  "description": "",
  "sources": "",
  "used_for": ""
}

### VITAMINS UPDATE
PATCH http://localhost:3000/vitamins/3.json
# Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NjE2ODk2Mjh9.g6epaGkcCgj9dJUqucOaFrcafxbhFXXUlWjvtWNSDOU
Content-Type: application/json

{
  "name": "Vitamin B3",
  "description": "Helps convert food into energy",
  "sources": "",
  "used_for": ""
}

### VITAMINS DELETE
DELETE http://localhost:3000/vitamins/6.json

###############USERS#######################################

### user create (sign up)
POST http://localhost:3000/users
Content-Type: application/json

{
  "first_name": "test",
  "last_name": "test",
  "age": 44,
  "email": "test@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions
Content-Type: application/json

{
  "email": "mike@mike.com",
  "password": "password"
}




###############LIST-OF-VITAMINS#######################################

### Appointments
GET http://localhost:3000/lists_of_vitamins.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NjQzODA2NzB9.QicMuQR6nqyxfona3X4EfD_c9lg697NB3p2NnwKwY9o

### LIST-OF-VITAMINS SHOW
GET http://localhost:3000/lists_of_vitamins/486.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NjQzODA2NzB9.QicMuQR6nqyxfona3X4EfD_c9lg697NB3p2NnwKwY9o


### LIST-OF-VITAMINS create
POST http://localhost:3000/lists_of_vitamins.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NjM5NTM1MTZ9.rqehwN1X1cRqMKqRR-FMQkLZWWTzWCw8UTZhWtz5Of0
Content-Type: application/json

{

 "vitamin_id": 7

}

### LIST-OF-VITAMINS UPDATE
PATCH http://localhost:3000/lists_of_vitamins/485.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NjQ0MDg0NTl9.6ASdOn0LDzQpefNYvoZbhiuvhXAF0bFbK_-ts-ROhQg
Content-Type: application/json

{
"quantity": 4


}

### LIST-OF-VITAMINS DELETE
DELETE http://localhost:3000/lists_of_vitamins/307.json



###############--APPOINTMENTS--#######################################

### APPOINTMENTS INDEX
GET http://localhost:3000/appointments.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NjQzODA2NzB9.QicMuQR6nqyxfona3X4EfD_c9lg697NB3p2NnwKwY9o

### Appointments SHOW
GET http://localhost:3000/appointments/19.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NjQzODA2NzB9.QicMuQR6nqyxfona3X4EfD_c9lg697NB3p2NnwKwY9o


### Appointments create
POST http://localhost:3000/appointments.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NjQzOTkzOTF9.TujMkY1Zmqd4NyTdq40MqDPrRjNJw-SiEMmHWQy3J9o
Content-Type: application/json

{
  "address": "san francisco,ca",
 "doctor_id": 10,
"date": "2022-09-30",
"phone_number": 4154180162

}

### Appointments UPDATE
PATCH http://localhost:3000/appointments/3.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NjQ0MDgxMzV9.P4Ke2U1c6Rxfoqtb4TQsIDYdOsWU9uV4IRq-0nFF9Io
Content-Type: application/json

{
"doctor_id": 4,
"date": "2022-09-26"

}

### LIST-OF-VITAMINS DELETE
DELETE http://localhost:3000/appointments/4.json


###############--doctors--#######################################

### doctors INDEX
GET http://localhost:3000/doctors.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NjQzODA2NzB9.QicMuQR6nqyxfona3X4EfD_c9lg697NB3p2NnwKwY9o

### doctors SHOW
GET http://localhost:3000/doctors/1.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NjQzODA2NzB9.QicMuQR6nqyxfona3X4EfD_c9lg697NB3p2NnwKwY9o


### doctors create
POST http://localhost:3000/doctors.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NjQzOTkzOTF9.TujMkY1Zmqd4NyTdq40MqDPrRjNJw-SiEMmHWQy3J9o
Content-Type: application/json

{
 "speciality": "Urology"

}

### doctors UPDATE
PATCH http://localhost:3000/doctors/3.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NjQzOTkzOTF9.TujMkY1Zmqd4NyTdq40MqDPrRjNJw-SiEMmHWQy3J9o
Content-Type: application/json

{
"doctor_id": 1

}

### LIST-OF-VITAMINS DELETE
DELETE http://localhost:3000/doctors/3.json