### VITAMINS INDEX
GET http://localhost:3000/vitamins.json


### VITAMINS SHOW
GET http://localhost:3000/vitamins/7.json


### VITAMINS CREATE
POST http://localhost:3000/vitamins.json
# Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NjE2ODk2Mjh9.g6epaGkcCgj9dJUqucOaFrcafxbhFXXUlWjvtWNSDOU
Content-Type: application/json

{
  "name": "Vitamin B Complex",
  "description": "",
  "sources": "",
  "used_for": ""
}

### VITAMINS UPDATE
PATCH http://localhost:3000/vitamins/3.json
# Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NjE2ODk2Mjh9.g6epaGkcCgj9dJUqucOaFrcafxbhFXXUlWjvtWNSDOU
Content-Type: application/json

{
  "name": "Vitamin B3",
  "description": "Helps convert food into energy",
  "sources": "",
  "used_for": ""
}

### VITAMINS DELETE
DELETE http://localhost:3000/vitamins/6.json

###############USERS#######################################

### user create (sign up)
POST http://localhost:3000/users
Content-Type: application/json

{
  "first_name": "Mary",
  "last_name": "Blanc",
  "email": "mary@mary.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions
Content-Type: application/json

{
  "email": "mike@mike.com",
  "password": "password"
}


###############LIST-OF-VITAMINS#######################################

### LIST-OF-VITAMINS INDEX
GET http://localhost:3000/lists_of_vitamins.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NjM5NDczMjR9.VmsOeSKAm7LRZSVr5mr7L4MliBqZm-JdI_nRYFY0h50

### LIST-OF-VITAMINS SHOW
GET http://localhost:3000/lists_of_vitamins/286.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NjM5NDczMjR9.VmsOeSKAm7LRZSVr5mr7L4MliBqZm-JdI_nRYFY0h50


### LIST-OF-VITAMINS create
POST http://localhost:3000/lists_of_vitamins.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NjM5NTM1MTZ9.rqehwN1X1cRqMKqRR-FMQkLZWWTzWCw8UTZhWtz5Of0
Content-Type: application/json

{

 "vitamin_id": 7

}

### LIST-OF-VITAMINS UPDATE
PATCH http://localhost:3000/lists_of_vitamins/361.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NjM5NDczMjR9.VmsOeSKAm7LRZSVr5mr7L4MliBqZm-JdI_nRYFY0h50
Content-Type: application/json

{
"quantity": 4,
"intake_quantity": 1

}

### LIST-OF-VITAMINS DELETE
DELETE http://localhost:3000/lists_of_vitamins/307.json