# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)

user = User.new(
  first_name: "mike",
  last_name: "marquez",
  email: "mike@mike.com",
  password_digest: "password",
  age: 22,
)
user.save!

Vitamin.create!(
  [{ name: "Vitamin B2", image_url: "https://i0.wp.com/curejoy.com/wp-content/uploads/2018/05/Foods-rich-in-vitamin-b2.jpg?fit=1200%2C627&ssl=1", used_for: "Helps convert food into energy and\nsupports healthy skin, hair, blood & brain",
     images: "https://st2.depositphotos.com/7341970/10438/v/950/depositphotos_104389176-stock-illustration-vitamin-b2-letter-shape.jpg",
     deficiency: "Redness and swelling of the lining of the throat and mouth, sore throat, sores or cracks in the corners of the mouth and the lips, inflamed and red tongue, skin disorders." },
   { name: "Vitamin B7", image_url: "https://shopgiejo.com/wp-content/uploads/2022/02/THE-BEST-DIETARY-SOURCES-OF-BIOTIN-VITAMIN-B7-min-scaled.jpg",
     used_for: "Helps convert food to energy & break\ndown glucose",
     images: "https://st2.depositphotos.com/7341970/10438/v/950/depositphotos_104389338-stock-illustration-vitamin-b7-letter-shape.jpg",
     deficiency: "Nausea, Anorexia, Depression, hallucination." },
   { name: "Vitamin B1",
     image_url: "https://www.nutritionadvance.com/wp-content/uploads/2020/11/thiamin-foods.jpg",
     used_for: "Helps convert food into energy and is\ncritical for nerve function",
     images: "https://previews.123rf.com/images/svshot/svshot1802/svshot180200037/96264324-gold-pill-capsule-or-gold-drop-with-vitamin-b1-on-a-transparent-background-medical-template-.jpg",
     deficiency: "Fatigue, depression, irritability, headache, nausea, abdominal discomfort, trouble digesting carbohydrates." },
   { name: "Calcium", image_url: "https://www.hawaiipacifichealth.org/media/8882/getting-enough-calcium-for-strong-healthy-bones-web.jpg",
     used_for: "Bone health, muscle conctraction, cardiovasculaire system",
     images: "https://st2.depositphotos.com/5366154/12154/v/950/depositphotos_121541622-stock-illustration-calcium-mineral-blue-icon-vector.jpg",
     deficiency: "Muscle cramps and spasms, brittle nails, memory loss, confusion, depresion, bone fractures, tingling or/and numbness of the face, feet and hands." },
   { name: "Vitamin A", image_url: "https://www.healthifyme.com/blog/wp-content/uploads/2018/07/vitamin-a-feature.jpeg",
     used_for: "healthy vision, skin, bones, teeth\n& reproduction",
     images: "https://img.freepik.com/premium-vector/pink-vitamin-medicine-capsule-fruits-vegetables-that-neutralize-free-radicals_228260-314.jpg?w=740",
     deficiency: "Night blindness (early) leading to full blindness, Dry eyes, skin, and other tissues, Increased infections, Thinning and ulceration of the cornea, Oval, triangular, or irregular foamy patches on the white of the eye, Dry hair , Pruritis ,Broken fingernails." },
   { name: "Vitamin E", image_url: "https://www.healthkart.com/connect/wp-content/uploads/2017/09/banner-7.jpg",
     used_for: "Acts an an antioxidant, helps stabilize\ncell membranes",
     images: "https://img.freepik.com/premium-vector/electron-vitamin-e-minerals-complex-glossy-vitamins-pills-capsules-pill-healthy-food-supplement_228260-565.jpg?w=2000",
     deficiency: "Loss of muscle mass, problems with vision, muscle weakness, unsteady walking" },
   { name: "Vitamin D", image_url: "https://images.healthshots.com/healthshots/en/uploads/2022/03/28211325/Vitamin-d-foods.jpg",
     used_for: "Strengthens and helps form bones & teeth\nvia calcium & phosphorus",
     images: "https://st2.depositphotos.com/5366154/10772/v/950/depositphotos_107728052-stock-illustration-vitamn-d-icon-drop-gold.jpg",
     deficiency: "Rickets in children, soft and weak bones." },
   { name: "Magnesium", image_url: "https://i0.wp.com/cdn-prod.medicalnewstoday.com/content/images/articles/319/319481/foods-rich-in-magnesium.jpg?w=1155&h=1541",
     used_for: "Supporting muscle and nerve function and energy production",
     images: "https://st2.depositphotos.com/5366154/12159/v/950/depositphotos_121596412-stock-illustration-magnesium-mineral-blue-icon-vector.jpg",
     deficiency: "Sleep disorders, restless leg syndrome, irritability, anxiety and agitation, abnormal heart rythms, vomiting, nausea, low blood pressure, muscle cramping, hyperventilation, confusion, seizures, and week nail growth." },
   { name: "ZINC", image_url: "https://www.healthifyme.com/blog/wp-content/uploads/2021/09/Why-you-Should-Include-Zinc-Rich-Foods-in-Your-Diet.jpg",
     used_for: "Immune function, wound healing, blood clotting, thyroid function,and maintaing vision",
     images: "https://st2.depositphotos.com/5366154/12159/v/950/depositphotos_121598830-stock-illustration-zinc-mineral-blue-icon-vector.jpg",
     deficiency: "Low energy, Insomnia, Loss of taste or smell, Poor memory, Loss of libido, Slow thinking process,abnormal hair loss." },
   { name: "Vitamin C", image_url: "https://blog.nasm.org/hubfs/vitamin-c.jpg",
     used_for: "Acts as an antioxidant, helps make new\ncells, & improves immune system",
     images: "https://st2.depositphotos.com/1810600/9598/v/600/depositphotos_95989768-stock-illustration-vitamin-c-icon.jpg",
     deficiency: "Bleeding gums, Lowered resistance to infection, Slowed wound healing, Dry, splitting hair, Gingivitis, Nosebleeds , Weight gain, Dry skin, Painful joints, Weakened tooth enamel, Scurvy." },
   { name: "Vitamin B12", image_url: "https://drgreenmom.com/wp-content/uploads/2022/08/b12-foods-3.jpg",
     used_for: "Breaks down fatty acids & amino acids,\nhelps make red blo cells",
     images: "https://www.clancymedicalgroup.com/wp-content/uploads/Vitamin-B.jpg",
     deficiency: "Tingling sensation in the toes and fingers, fatigue, nervousness shortness of breath numbness, diarrhea, and servere deficiency can result in nerve damage." },
   { name: "Vitamin K",
     image_url: "https://potentash.com/wp-content/uploads/2021/08/Board-with-vitamin-K-written-on-it-and-green-foods-all-around-it.jpg",
     used_for: "Essential for blood clotting and helping to\nregulate blood calcium",
     images: "https://img.freepik.com/premium-vector/vitamin-k-green-glossy-pill-vector-illustration-health-care-organic-symbol-food-dietary_390775-816.jpg?w=2000",
     deficiency: "Gums bleed, gastrointestinal problems, weak bones, excessive bleeding" }]
)

Doctor.create!(
  [{ name: "jhon",
     address: "",
     speciality: "orthopedic",
     image_url: "https://cdn4.iconfinder.com/data/icons/medical-worker-avatar-1/64/orthopedic_doctor_bone_surgeon_medical__avatar_people-512.png" },
   { name: "Janelle",
     address: "",
     speciality: "Dermatology",
     image_url: "https://cdn4.iconfinder.com/data/icons/medical-worker-avatar-1/64/dermatologist_doctor_dermatology_medical_skin_avatar_people-512.png" },
   { name: "",
     address: "",
     speciality: "Allergy and immunology",
     image_url: "https://myupchar-banner.s3.ap-south-1.amazonaws.com/widget/avatar/doctor-avatar-female.png" },
   { name: "",
     address: "",
     speciality: "Family medicine",
     image_url: "https://st2.depositphotos.com/1006318/5909/v/950/depositphotos_59095203-stock-illustration-medical-doctor-profile.jpg" },
   { name: "",
     address: "",
     speciality: "Urology", image_url: "https://cdn4.iconfinder.com/data/icons/medical-worker-avatar-1/64/urology_doctor_kidneys_ureters_bladder_avatar_people-512.png" }, { name: "", address: "", speciality: "Pathology", image_url: "https://thumbs.dreamstime.com/b/black-mix-icon-pathologist-pharmacology-experiment-medical-biochemist-diagnosis-160883648.jpg" },
   { name: "",
     address: "",
     speciality: "Psychiatry",
     image_url: "https://cdn3.iconfinder.com/data/icons/medical-avatars/128/06-512.png" },
   { name: "",
     address: "",
     speciality: "Surgery",
     image_url: "https://img.freepik.com/premium-psd/medical-surgeon-specialist-doctor-avatar-3d-illustration-3d-icon-editable-color-isolated_384205-553.jpg?w=2000" },
   { name: "",
     address: "",
     speciality: "Neurology",
     image_url: "https://previews.123rf.com/images/bsd555/bsd5552008/bsd555200801631/153733483-neurological-department-rgb-color-icon-neurological-science-and-surgery-brain-disorders-neurology-di.jpg" },
   { name: "",
     address: "",
     speciality: "Anesthesiology",
     image_url: "https://c8.alamy.com/comp/2DFJ8B6/anesthesiologist-medical-worker-color-icon-vector-illustration-2DFJ8B6.jpg" }]
)
